#Cargo.toml
[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.2", features=["json"]}
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
serde = "1.0.152"
chrono = "^0.4"
google_maps = "3.1"
tokio = "1.26.0"
serde_json = "1.0.94"
winping = "0.10.1"
dns-lookup = "1.0.8"
url = "2.3.1"

[dependencies.rocket_dyn_templates]
features = ["handlebars"]

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]